config/routes.rb
Rails.application.routes.draw do

  root :to => 'login#login'

  post "login/findlogin"
  get "login/login"
  get "login/unlogin"
  resources :systemlogs
  resources :retcauses
  resources :comments
  resources :articles
  resources :admins
  get 'logisticbuycar/update'
  get 'logisticbuycar/destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :sellers do

    resources :productclas

    resources :products

    resources :admins

    resources :sellerusers
    resources :buycars do
      #resources :logisticbuycar
      get 'logisticbuycar/index'
      get 'logisticbuycar/edit'
      get 'logisticbuycar/new'
      collection do
        get 'editstatus'
      end
      resources :retoforders do
        member do
          get 'setretok'
          get 'setretno'
          get 'setlogisticok'
        end
      end
      member do
        post 'setsellererr'
      end
    end
    resources :notices
    resources :weixinmenus
    resources :articles do
      resources :comments do
        member do
          get  'publecomm'
          get  'publedel'
        end
      end
    end
    resources :sellermodels do
      resources :modelconts
    end
  end

  resources :logistics
  resources :logisticorders
  resources :stables

  resources :recepitaddres

  resources :orders
  resources :userpwds
  resources :users

  resources :notices

  resources :weixinmenus do
    collection do
      get 'saveweixin'
      get 'saveid'
      get 'delid'
      get 'loading'
    end
  end

  resources :apis do
    collection do
      get 'getreceoitdefault'
      get 'getseller'
      get 'getproductlist'
      get 'getproductcontent'
      get 'getproname'
      get 'getrecepit'
      get 'getbuycarfrom'
      get 'getbuycarlist'
      get 'getreceoitadd'
      get 'getrecepitone'
      get 'getreceoitedit'
      get 'getreceoitdel'
      get 'getreceoitdefa'
      get 'getnotice'
      post 'weixingetpost'
      get 'weixingetpost'
      get 'getweixinimg'
      get 'getwxopenid'
      get 'getbuycaradd'
      get 'setreceive'
      get 'getbuycarplay'
      get 'getbuycarconfirm'
      get 'getuserupname'
      get 'setuserupname'
      get 'getthreename'
      get 'getsenondname'
      get 'getreferralname'
      get 'getwxpublicqrcode'
      get 'getwxpubliopenid'
      get 'getsellerqrcode'
      get 'getuserpswds'
      get 'setuserpswds'
      get 'getak'
      get 'getwxgetrich'
      get 'getarticles'
      get 'getarticleopenid'
      get 'getarticlecontent'
      get 'setcomment'
      get 'getsystemlog'
      get 'getbuycaraftersales'
      get 'setafterone'
      get 'getlogistics'
      get 'getafterlogistics'
      get 'setlogistics'
      get 'getretcauses'
      get 'getwxposanopenid'
      get 'getbuycardel'
      post 'prepaytrue'
      get 'getbuycartruemoney'
    end
  end

  resources :weixinlogs

end

app/models/admin.rb
class Admin < ApplicationRecord
  has_secure_password
  belongs_to :seller
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :seller
  has_many :comments
end

app/models/buycar.rb
class Buycar < ApplicationRecord
  belongs_to :selleruser
  has_many :orders

  has_many :logisticorders
  has_many :buycarsigns

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/logistic.rb
class Logistic < ApplicationRecord

  has_many :logisticorders
end

app/models/modelcont.rb
class Modelcont < ApplicationRecord
  belongs_to :sellermodel
end

app/models/notice.rb
class Notice < ApplicationRecord

  belongs_to :seller

  has_attached_file :noticeimg, :url => "/:attachment/:id/:basename.:extension",  :path => ":rails_root/public/:attachment/:id/:basename.:extension"
  do_not_validate_attachment_file_type :noticeimg

end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :buycar

  has_many :products
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :productcla
  belongs_to :seller
  belongs_to :order

  has_attached_file :productimg, :url => "/:attachment/:id/:basename.:extension",  :path => ":rails_root/public/:attachment/:id/:basename.:extension"
  do_not_validate_attachment_file_type :productimg
end

app/models/productcla.rb
class Productcla < ApplicationRecord
  belongs_to :seller
  has_many :products
end

app/models/receive.rb
class Receive < ApplicationRecord
end

app/models/retcause.rb
class Retcause < ApplicationRecord
end

app/models/retoforder.rb
class Retoforder < ApplicationRecord
  has_many :sellerusers
end

app/models/seller.rb
class Seller < ApplicationRecord
  has_many :productclas

  has_many :sellerusers
  has_many :buycars

  has_many :products
  has_many :admins

  has_many :notices

  has_many :weixinmenus

  has_many :articles
  has_many :sellermodels

  has_attached_file :sellerimage, :url => "/:attachment/:id/:basename.:extension",  :path => ":rails_root/public/:attachment/:id/:basename.:extension"
  do_not_validate_attachment_file_type :sellerimage

  has_attached_file :qrcode, :url => "/:attachment/:id/:basename.:extension",  :path => ":rails_root/public/:attachment/:id/:basename.:extension"
  do_not_validate_attachment_file_type :qrcode
end

app/models/selleruser.rb
class Selleruser < ApplicationRecord
  belongs_to :seller
  belongs_to :user
  belongs_to :retoforder

  has_many :buycars
  has_many :systemlogs
end

app/models/stable.rb
class Stable < ApplicationRecord
end

app/models/systemlog.rb
class Systemlog < ApplicationRecord
  belongs_to :selleruser
end

app/models/user.rb
class User < ApplicationRecord

  has_many :sellerusers
  has_many :recepitaddres

  has_one :userpwd
end

app/models/userpwd.rb
class Userpwd < ApplicationRecord
  has_secure_password
  belongs_to :user
end

app/models/weixinlog.rb
class Weixinlog < ApplicationRecord

end

app/models/weixinmenu.rb
class Weixinmenu < ApplicationRecord
  belongs_to :seller
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  before_action :authenticate_role
  before_action :set_notice, only: [:show, :edit, :update, :destroy]
  before_action :set_seller, only: [:index, :show, :new, :edit, :update, :destroy]

  def index
    if @seller
      @notices = @seller.notices
    else
      @notices = Notice.where('seller_id is null')
    end

  end

  def show
  end

  def edit
    @notices = Notice.all
  end

  def new
    @notice = Notice.new
    if @seller
      @notice.seller_id=@seller.id
    end
  end

  def create

    @notice = Notice.new(notice_params)
    if notice_params[:recommend]
      @notice.recommend = notice_params[:recommend]
    else
      @notice.status = notice_params[:status]
      @seller = Seller.find(@notice.seller_id)
    end
    respond_to do |format|
      if @notice.save
        if notice_params[:seller_id]
          format.html { redirect_to seller_notices_path(@seller), notice: 'Dgt was successfully created.' }
          format.json { render :show, status: :ok, location: @seller }
        else
          format.html { redirect_to notices_path, notice: 'Dgt was successfully created.' }
        end

      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @notice.update(notice_params)
        if @notice.seller_id
          @seller = Seller.find(@notice.seller_id)
          format.html { redirect_to seller_notices_path(@seller), notice: 'Dgt was successfully updated.' }
        else
          format.html { redirect_to notices_path, notice: 'Dgt was successfully updated.' }
        end
        format.json { render :show, status: :ok, location: @notice }
      else
        format.html { render :edit }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @notice.destroy
    respond_to do |format|
      if @notice.seller_id
        @seller = Seller.find(@notice.seller_id)
        format.html { redirect_to seller_notices_path(@seller), notice: '删除成功' }
      else
        format.html { redirect_to notices_path, notice: '删除成功' }
      end
      format.json { head :no_content }
    end
  end

  private

# Use callbacks to share common setup or constraints between actions.
  def set_notice
    @notice = Notice.find(params[:id])
  end

  def set_seller
    if params[:seller_id]
      @seller = Seller.find(params[:seller_id])
    end
  end

  def notice_params
    params.require(:notice).permit(:noticeimg, :recommend, :status, :seller_id)
  end
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/views/notices/_form.html.erb
<script>
    $(document).ready(function() {
        $('.i-checks').iCheck({
            checkboxClass: 'icheckbox_square-green',
            radioClass: 'iradio_square-green'
        });
        $('#statuscheck').on('ifChecked',function(event){
            $('#status').val(1);
        });
        $('#statuscheck').on('ifUnchecked',function(event){
            $('#status').val(0);
        });
    });

</script>


<div class="ibox-content form-horizontal m-t">
  <div class="form-group">
    <%= form_for([@notice],:html => {:class=>'form-horizontal m-t',:multipart => true}) do |f| %>
        <div class="form-group">
          <label class="col-sm-3 control-label">新增通告：</label>
          <div class="col-sm-6 text-center">
            <%= f.file_field :noticeimg,class:"form-control",:onchange => "readURL(this)" %>
            <img id="img1" width="600px" src=<%= @notice.noticeimg.url %>>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label">是否显示：</label>
          <div class="col-sm-6">
            <% if @seller%>
                <%= f.hidden_field :status,class:"form-control",id:'status' %>
            <%else%>
                <%= f.hidden_field :recommend,class:"form-control",id:'status' %>
            <%end%>
            <%= f.hidden_field :seller_id,class:"form-control",id:'seller' %>
            <label>
              <input type="checkbox" class="i-checks" id="statuscheck"> 显示</label>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label"></label>
          <div class="col-sm-6 text-right">
            <%= f.submit '确定',class: "btn btn-w-m btn-primary",id:'smt' %>&nbsp;
            <% if @seller%>
                <%= link_to "返回",seller_notices_path(@seller),class: "btn btn-w-m btn-primary " %>
            <%else%>
                <%= link_to "返回",notices_path,class: "btn btn-w-m btn-primary " %>
            <%end%>

          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/notices/edit.html.erb
<%= render 'layerbegin' %>
<div class="col-lg-12">
  <div class="ibox float-e-margins">
    <div class="ibox-title">
      <h3>编辑通告</h3>
    </div>
    <%= render 'form', notice: @notice %>
  </div>
</div>
<%=render 'layerend' %>

app/views/notices/index.html.erb
<%= render 'layerbegin' %>
<div class="col-lg-12">
  <div class="ibox float-e-margins">
    <div class="ibox-title">
      <h3>通告</h3>
    </div>
    <div class="ibox-content">
      <table class="table table-hover table-bordered text-center">
        <thead>
        <tr>
          <th class="text-center">通告</th>
          <th class="text-center">操作</th>
        </tr>
        </thead>
        <tbody>
        <% @notices.each do |notice| %>
            <tr>
              <td><%= notice.noticeimg %></td>
              <td>
                <% if @seller%>
                    <%= link_to '编辑',edit_seller_notice_path(@seller,notice) %>
                    <%= link_to '删除', notice, method: :delete, data: { confirm: '确认删除?' } %>
                <%else%>
                    <%= link_to '编辑',edit_notice_path(notice) %>
                    <%= link_to '删除', notice, method: :delete, data: { confirm: '确认删除?' } %>
                <%end%>
              </td>
            </tr>
        <% end %>
        </tbody>
      </table>
      <% if @seller%>
          <%= link_to "返回",seller_path(@seller),class: "btn btn-w-m btn-info " %>
      <%end%>
      <div class="btn-group  btn-w-m pull-right" role="group">
        <% if @seller%>
            <%= link_to "新增",new_seller_notice_path,class: "btn btn-w-m btn-primary " %>
        <%else%>
            <%= link_to "新增",new_notice_path,class: "btn btn-w-m btn-primary " %>
        <%end%>
      </div>
      <br>
    </div>
  </div>
</div>
<%=render 'layerend' %>

app/views/notices/new.html.erb
<%= render 'layerbegin' %>
<div class="col-lg-12">
  <div class="ibox float-e-margins">
    <div class="ibox-title">
      <h3>新增通告</h3>
    </div>
    <%= render 'form', notice: @notice %>
  </div>
</div>
<%=render 'layerend' %>