config/routes.rb
Rails.application.routes.draw do

  root :to => 'login#login'

  post "login/findlogin"
  get "login/login"
  get "login/unlogin"
  resources :systemlogs
  resources :retcauses
  resources :comments
  resources :articles
  resources :admins
  get 'logisticbuycar/update'
  get 'logisticbuycar/destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :sellers do

    resources :productclas

    resources :products

    resources :admins

    resources :sellerusers
    resources :buycars do
      #resources :logisticbuycar
      get 'logisticbuycar/index'
      get 'logisticbuycar/edit'
      get 'logisticbuycar/new'
      collection do
        get 'editstatus'
      end
      resources :retoforders do
        member do
          get 'setretok'
          get 'setretno'
          get 'setlogisticok'
        end
      end
      member do
        post 'setsellererr'
      end
    end
    resources :notices
    resources :weixinmenus
    resources :articles do
      resources :comments do
        member do
          get  'publecomm'
          get  'publedel'
        end
      end
    end
    resources :sellermodels do
      resources :modelconts
    end
  end

  resources :logistics
  resources :logisticorders
  resources :stables

  resources :recepitaddres

  resources :orders
  resources :userpwds
  resources :users

  resources :notices

  resources :weixinmenus do
    collection do
      get 'saveweixin'
      get 'saveid'
      get 'delid'
      get 'loading'
    end
  end

  resources :apis do
    collection do
      get 'getreceoitdefault'
      get 'getseller'
      get 'getproductlist'
      get 'getproductcontent'
      get 'getproname'
      get 'getrecepit'
      get 'getbuycarfrom'
      get 'getbuycarlist'
      get 'getreceoitadd'
      get 'getrecepitone'
      get 'getreceoitedit'
      get 'getreceoitdel'
      get 'getreceoitdefa'
      get 'getnotice'
      post 'weixingetpost'
      get 'weixingetpost'
      get 'getweixinimg'
      get 'getwxopenid'
      get 'getbuycaradd'
      get 'setreceive'
      get 'getbuycarplay'
      get 'getbuycarconfirm'
      get 'getuserupname'
      get 'setuserupname'
      get 'getthreename'
      get 'getsenondname'
      get 'getreferralname'
      get 'getwxpublicqrcode'
      get 'getwxpubliopenid'
      get 'getsellerqrcode'
      get 'getuserpswds'
      get 'setuserpswds'
      get 'getak'
      get 'getwxgetrich'
      get 'getarticles'
      get 'getarticleopenid'
      get 'getarticlecontent'
      get 'setcomment'
      get 'getsystemlog'
      get 'getbuycaraftersales'
      get 'setafterone'
      get 'getlogistics'
      get 'getafterlogistics'
      get 'setlogistics'
      get 'getretcauses'
      get 'getwxposanopenid'
      get 'getbuycardel'
      post 'prepaytrue'
      get 'getbuycartruemoney'
    end
  end

  resources :weixinlogs

end

app/models/admin.rb
class Admin < ApplicationRecord
  has_secure_password
  belongs_to :seller
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :seller
  has_many :comments
end

app/models/buycar.rb
class Buycar < ApplicationRecord
  belongs_to :selleruser
  has_many :orders

  has_many :logisticorders
  has_many :buycarsigns

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/logistic.rb
class Logistic < ApplicationRecord

  has_many :logisticorders
end

app/models/modelcont.rb
class Modelcont < ApplicationRecord
  belongs_to :sellermodel
end

app/models/notice.rb
class Notice < ApplicationRecord

  belongs_to :seller

  has_attached_file :noticeimg, :url => "/:attachment/:id/:basename.:extension",  :path => ":rails_root/public/:attachment/:id/:basename.:extension"
  do_not_validate_attachment_file_type :noticeimg

end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :buycar

  has_many :products
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :productcla
  belongs_to :seller
  belongs_to :order

  has_attached_file :productimg, :url => "/:attachment/:id/:basename.:extension",  :path => ":rails_root/public/:attachment/:id/:basename.:extension"
  do_not_validate_attachment_file_type :productimg
end

app/models/productcla.rb
class Productcla < ApplicationRecord
  belongs_to :seller
  has_many :products
end

app/models/receive.rb
class Receive < ApplicationRecord
end

app/models/retcause.rb
class Retcause < ApplicationRecord
end

app/models/retoforder.rb
class Retoforder < ApplicationRecord
  has_many :sellerusers
end

app/models/seller.rb
class Seller < ApplicationRecord
  has_many :productclas

  has_many :sellerusers
  has_many :buycars

  has_many :products
  has_many :admins

  has_many :notices

  has_many :weixinmenus

  has_many :articles
  has_many :sellermodels

  has_attached_file :sellerimage, :url => "/:attachment/:id/:basename.:extension",  :path => ":rails_root/public/:attachment/:id/:basename.:extension"
  do_not_validate_attachment_file_type :sellerimage

  has_attached_file :qrcode, :url => "/:attachment/:id/:basename.:extension",  :path => ":rails_root/public/:attachment/:id/:basename.:extension"
  do_not_validate_attachment_file_type :qrcode
end

app/models/selleruser.rb
class Selleruser < ApplicationRecord
  belongs_to :seller
  belongs_to :user
  belongs_to :retoforder

  has_many :buycars
  has_many :systemlogs
end

app/models/stable.rb
class Stable < ApplicationRecord
end

app/models/systemlog.rb
class Systemlog < ApplicationRecord
  belongs_to :selleruser
end

app/models/user.rb
class User < ApplicationRecord

  has_many :sellerusers
  has_many :recepitaddres

  has_one :userpwd
end

app/models/userpwd.rb
class Userpwd < ApplicationRecord
  has_secure_password
  belongs_to :user
end

app/models/weixinlog.rb
class Weixinlog < ApplicationRecord

end

app/views/admins/_form.html.erb
<script>

$(document).ready(function(){
    $('.i-checks').iCheck({
        checkboxClass: 'icheckbox_square-green',
        radioClass: 'iradio_square-green'
    });

    $('#statuscheck').on('ifChecked',function(event){
        $('#statusinput').val(1);
    });
    $('#statuscheck').on('ifUnchecked',function(event){
        $('#statusinput').val(0);
    });
    if($('#statusinput').val() != '' && $('#statusinput').val() != '0'){
        $('#statuscheck').iCheck('check');
    }

    $('#smt').click(function(){
        if($('#username').val()==''){
            toastr.error('用户名不能为空');
            return false;
        }
        if($('#login').val()==''){
            toastr.error('帐号不能为空');
            return false;
        }
        if($('#password').val()==''){
            toastr.error('密码不能为空');
            return false;
        }
        if($('#password_confirmation').val()==''){
            toastr.error('再次输入密码不能为空');
            return false;
        }
        if(($('#password_confirmation').val())!=($('#password').val()))
        {
            toastr.error('两次输入的密码不相同');
            return false;
        }
    });

});

</script>

<div class="ibox-content form-horizontal m-t">
  <div class="form-group">
    <%= form_for([@seller,@admin],:html => {:class=>'form-horizontal m-t',:multipart => true}) do |f| %>
        <div class="form-group">
          <label class="col-sm-3 control-label">用户名：</label>
          <div class="col-sm-6">
            <%= f.text_field :username,class:"form-control",id:'username' %>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label">帐号：</label>
          <div class="col-sm-6">
            <%= f.text_field :login,class:"form-control",id:'login' %>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label">密码：</label>
          <div class="col-sm-6">
            <%= f.password_field :password,class:"form-control",id:'password' %>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label">再次输入密码：</label>
          <div class="col-sm-6">
            <%= f.password_field :password_confirmation,class:"form-control",id:'password_confirmation' %>
          </div>
        </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label">状态：</label>
          <div class="col-sm-6">
            <%= f.hidden_field :status,class:"form-control",id:'statusinput' %>
            <label>
              <input type="checkbox" class="i-checks" id="statuscheck"> 启用</label>
          </div>
        </div>

        <div class="form-group">
          <label class="col-sm-3 control-label">权限：</label>
          <div class="col-sm-6">
            <%= f.text_field :auth,class:"form-control" %>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label">入侵次数：</label>
          <div class="col-sm-6">
            <%= f.text_field :nids,class:"form-control" %>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label">密码错误次数：</label>
          <div class="col-sm-6">
            <%= f.text_field :errpwd,class:"form-control" %>
          </div>
        </div>
         <div class="form-group">
          <label class="col-sm-3 control-label"></label>
          <div class="col-sm-6 text-right">
            <%= f.submit '确定',class: "btn btn-w-m btn-primary",id:'smt' %>&nbsp;
            <%if @seller != nil%>
                <%= link_to "返回",seller_admins_path(@seller),class: "btn btn-w-m btn-primary " %>
            <%else%>
                <%= link_to "返回",admins_path,class: "btn btn-w-m btn-primary " %>
            <%end%>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/admins/edit.html.erb
<%= render 'layerbegin' %>
<div class="col-lg-12">
  <div class="ibox float-e-margins">
    <div class="ibox-title">
      <h3>编辑管理员</h3>
    </div>
    <%= render 'form', admin: @admin %>
  </div>
</div>
<%=render 'layerend' %>

app/views/admins/index.html.erb
<%= render 'layerbegin' %>
<div class="col-lg-12">
  <div class="ibox float-e-margins">
    <div class="ibox-title">
      <h3>管理员管理</h3>
    </div>
    <div class="ibox-content" data-turbolinks="false">
      <table class="table table-hover table-bordered text-center">
        <thead>
        <tr>
          <th class="text-center">用户名</th>
          <th class="text-center">帐号</th>
          <th class="text-center">操作</th>
        </tr>
        </thead>
        <tbody>
        <% @admins.each do |admin| %>
            <tr>
              <td><%= admin.username %></td>
              <td><%= admin.login %></td>
              <td>
                <%if @seller != nil%>
                    <%= link_to '编辑',edit_seller_admin_path(@seller,admin) %>
                <%else%>
                    <%= link_to '编辑',edit_admin_path(admin) %>
                <%end%>
                <%= link_to '删除', [@seller,admin], method: :delete, data: { confirm: '确认删除?' } %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
      <%if @seller != nil%>
          <%= link_to "新增",new_seller_admin_path(@seller),class: "btn btn-w-m btn-primary pull-right" %>
          <%= link_to "返回",seller_path(@seller),class: "btn btn-w-m btn-info " %>
      <%else%>
          <%= link_to "新增",new_admin_path,class: "btn btn-w-m btn-primary pull-right" %>
      <%end%>
      <br>
    </div>
  </div>
</div>
<%=render 'layerend' %>

app/views/admins/new.html.erb
<%= render 'layerbegin' %>
<div class="col-lg-12">
  <div class="ibox float-e-margins">
    <div class="ibox-title">
      <h3>新增管理员</h3>
    </div>
    <%= render 'form'%>
  </div>
</div>
<%=render 'layerend' %>