config/routes.rb
Rails.application.routes.draw do

  root :to => 'login#login'

  post "login/findlogin"
  get "login/login"
  get "login/unlogin"
  resources :systemlogs
  resources :retcauses
  resources :comments
  resources :articles
  resources :admins
  get 'logisticbuycar/update'
  get 'logisticbuycar/destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :sellers do

    resources :productclas

    resources :products

    resources :admins

    resources :sellerusers
    resources :buycars do
      #resources :logisticbuycar
      get 'logisticbuycar/index'
      get 'logisticbuycar/edit'
      get 'logisticbuycar/new'
      collection do
        get 'editstatus'
      end
      resources :retoforders do
        member do
          get 'setretok'
          get 'setretno'
          get 'setlogisticok'
        end
      end
      member do
        post 'setsellererr'
      end
    end
    resources :notices
    resources :weixinmenus
    resources :articles do
      resources :comments do
        member do
          get  'publecomm'
          get  'publedel'
        end
      end
    end
    resources :sellermodels do
      resources :modelconts
    end
  end

  resources :logistics
  resources :logisticorders
  resources :stables

  resources :recepitaddres

  resources :orders
  resources :userpwds
  resources :users

  resources :notices

  resources :weixinmenus do
    collection do
      get 'saveweixin'
      get 'saveid'
      get 'delid'
      get 'loading'
    end
  end

  resources :apis do
    collection do
      get 'getreceoitdefault'
      get 'getseller'
      get 'getproductlist'
      get 'getproductcontent'
      get 'getproname'
      get 'getrecepit'
      get 'getbuycarfrom'
      get 'getbuycarlist'
      get 'getreceoitadd'
      get 'getrecepitone'
      get 'getreceoitedit'
      get 'getreceoitdel'
      get 'getreceoitdefa'
      get 'getnotice'
      post 'weixingetpost'
      get 'weixingetpost'
      get 'getweixinimg'
      get 'getwxopenid'
      get 'getbuycaradd'
      get 'setreceive'
      get 'getbuycarplay'
      get 'getbuycarconfirm'
      get 'getuserupname'
      get 'setuserupname'
      get 'getthreename'
      get 'getsenondname'
      get 'getreferralname'
      get 'getwxpublicqrcode'
      get 'getwxpubliopenid'
      get 'getsellerqrcode'
      get 'getuserpswds'
      get 'setuserpswds'
      get 'getak'
      get 'getwxgetrich'
      get 'getarticles'
      get 'getarticleopenid'
      get 'getarticlecontent'
      get 'setcomment'
      get 'getsystemlog'
      get 'getbuycaraftersales'
      get 'setafterone'
      get 'getlogistics'
      get 'getafterlogistics'
      get 'setlogistics'
      get 'getretcauses'
      get 'getwxposanopenid'
      get 'getbuycardel'
      post 'prepaytrue'
      get 'getbuycartruemoney'
    end
  end

  resources :weixinlogs

end

app/models/admin.rb
class Admin < ApplicationRecord
  has_secure_password
  belongs_to :seller
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :seller
  has_many :comments
end

app/models/buycar.rb
class Buycar < ApplicationRecord
  belongs_to :selleruser
  has_many :orders

  has_many :logisticorders
  has_many :buycarsigns

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/logistic.rb
class Logistic < ApplicationRecord

  has_many :logisticorders
end

app/models/modelcont.rb
class Modelcont < ApplicationRecord
  belongs_to :sellermodel
end

app/models/notice.rb
class Notice < ApplicationRecord

  belongs_to :seller

  has_attached_file :noticeimg, :url => "/:attachment/:id/:basename.:extension",  :path => ":rails_root/public/:attachment/:id/:basename.:extension"
  do_not_validate_attachment_file_type :noticeimg

end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :buycar

  has_many :products
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :productcla
  belongs_to :seller
  belongs_to :order

  has_attached_file :productimg, :url => "/:attachment/:id/:basename.:extension",  :path => ":rails_root/public/:attachment/:id/:basename.:extension"
  do_not_validate_attachment_file_type :productimg
end

app/models/productcla.rb
class Productcla < ApplicationRecord
  belongs_to :seller
  has_many :products
end

app/models/receive.rb
class Receive < ApplicationRecord
end

app/models/retcause.rb
class Retcause < ApplicationRecord
end

app/models/retoforder.rb
class Retoforder < ApplicationRecord
  has_many :sellerusers
end

app/models/seller.rb
class Seller < ApplicationRecord
  has_many :productclas

  has_many :sellerusers
  has_many :buycars

  has_many :products
  has_many :admins

  has_many :notices

  has_many :weixinmenus

  has_many :articles
  has_many :sellermodels

  has_attached_file :sellerimage, :url => "/:attachment/:id/:basename.:extension",  :path => ":rails_root/public/:attachment/:id/:basename.:extension"
  do_not_validate_attachment_file_type :sellerimage

  has_attached_file :qrcode, :url => "/:attachment/:id/:basename.:extension",  :path => ":rails_root/public/:attachment/:id/:basename.:extension"
  do_not_validate_attachment_file_type :qrcode
end

app/models/selleruser.rb
class Selleruser < ApplicationRecord
  belongs_to :seller
  belongs_to :user
  belongs_to :retoforder

  has_many :buycars
  has_many :systemlogs
end

app/models/stable.rb
class Stable < ApplicationRecord
end

app/models/systemlog.rb
class Systemlog < ApplicationRecord
  belongs_to :selleruser
end

app/models/user.rb
class User < ApplicationRecord

  has_many :sellerusers
  has_many :recepitaddres

  has_one :userpwd
end

app/models/userpwd.rb
class Userpwd < ApplicationRecord
  has_secure_password
  belongs_to :user
end

app/models/weixinlog.rb
class Weixinlog < ApplicationRecord

end

app/models/weixinmenu.rb
class Weixinmenu < ApplicationRecord
  belongs_to :seller
end

app/controllers/sellers_controller.rb
class SellersController < ApplicationController
  before_action :authenticate_role
  before_action :set_seller, only: [:show, :edit, :update, :destroy, :productcla]
  def index
    if session[:admin] == "admin"
      @sellers = Seller.all
    else
      @sellers = Seller.where("id = ?",session[:current_user_id])
    end
  end

  def edit
    @seller = Seller.find(params[:id])

  end

  def new
    @seller = Seller.new
  end


  def create
    @seller = Seller.new(seller_params)

    respond_to do |format|
      if @seller.save
        format.html { redirect_to sellers_path, notice: 'Unit was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @seller.update(seller_params)
        format.html { redirect_to sellers_path, notice: 'Unit was successfully updated.' }
        format.json { render :show, status: :ok, location: @seller }
      else
        format.html { render :edit }
        format.json { render json: @seller.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if session[:admin] == "admin"
      @seller.destroy
      respond_to do |format|
        format.html { redirect_to sellers_path, notice: '删除成功' }
        format.json { head :no_content }
      end
    else
      redirect_to sellers_path, notice: '删除失败'
    end
  end

def show
  @productclacount = @seller.productclas.count
end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_seller
    @seller = Seller.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def seller_params
    params.require(:seller).permit(:name, :summary, :tel, :address, :status, :shortname, :sellerimage, :appid, :secret, :weixinname, :qrcode)
  end

end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/views/sellers/_form.html.erb
<script>

$(document).ready(function(){
    $('.i-checks').iCheck({
        checkboxClass: 'icheckbox_square-green',
        radioClass: 'iradio_square-green'
    });

    $('#statuscheck').on('ifChecked',function(event){
        $('#statusinput').val(1);
    });
    $('#statuscheck').on('ifUnchecked',function(event){
        $('#statusinput').val(0);
    });
    if($('#statusinput').val() != '' && $('#statusinput').val() != '0'){
        $('#statuscheck').iCheck('check');
    }

    $('#smt').click(function(){
        if($('#name').val()==''){
            toastr.error('商家名称不能为空');
            return false;
        }
        if($('#shortname').val()==''){
            toastr.error('商家简称不能为空');
            return false;
        }
        if($('#tel').val()==''){
            toastr.error('商家电话不能为空');
            return false;
        }
        if($('#address').val()==''){
            toastr.error('商家地址不能为空');
            return false;
        }
    });

});

    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                $('#img1').attr('src', e.target.result);
            };
            reader.readAsDataURL(input.files[0]);
        }
    }

    function readURLqrcode(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                $('#qrcode1').attr('src', e.target.result);
            };
            reader.readAsDataURL(input.files[0]);
        }
    }


</script>
<div class="ibox-content form-horizontal m-t" >
  <div class="form-group">
    <%= form_for(@seller,:html => {:class=>'form-horizontal m-t',:multipart => true}) do |f| %>
        <div class="form-group">
          <label class="col-sm-3 control-label">商家名称：</label>
          <div class="col-sm-6">
            <%= f.text_field :name,class:"form-control",id:'name' %>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label">商家简称：</label>
          <div class="col-sm-6">
            <%= f.text_field :shortname,class:"form-control",id:'shortname' %>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label">二维码图片：</label>
          <div class="col-sm-6 text-center">
            <%= f.file_field :qrcode,class:"form-control",:onchange => "readURLqrcode(this)" %>
            <img id="qrcode1" width="600px" src=<%= @seller.qrcode.url %>>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label">电话：</label>
          <div class="col-sm-6">
            <%= f.text_field :tel,class:"form-control",id:'tel' %>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label">地址：</label>
          <div class="col-sm-6">
            <%= f.text_field :address,class:"form-control",id:'address' %>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label">状态：</label>
          <div class="col-sm-6">
            <%= f.hidden_field :status,class:"form-control",id:'statusinput' %>
            <label>
              <input type="checkbox" class="i-checks" id="statuscheck"> 启用</label>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label">商家appid：</label>
          <div class="col-sm-6">
            <%= f.text_field :appid,class:"form-control",id:'tel' %>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label">商家secret：</label>
          <div class="col-sm-6">
            <%= f.text_field :secret,class:"form-control",id:'tel' %>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label">appid申请微信号：</label>
          <div class="col-sm-6">
            <%= f.text_field :weixinname,class:"form-control",id:'tel' %>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label">token：</label>
          <div class="col-sm-6">
            <%= f.text_field :access_token,class:"form-control",id:'tel' %>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label">商家图片：</label>
          <div class="col-sm-6 text-center">
            <%= f.file_field :sellerimage,class:"form-control",:onchange => "readURL(this)" %>
            <img id="img1" width="600px" src=<%= @seller.sellerimage.url %>>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label">商家简介：</label>
          <div class="col-sm-6">
            <%= f.kindeditor :summary,class:"form-control" %>
          </div>
        </div>
         <div class="form-group">
          <label class="col-sm-3 control-label"></label>
          <div class="col-sm-6 text-right">
            <%= f.submit '确定',class: "btn btn-w-m btn-primary",id:'smt' %>&nbsp;<%= link_to "返回",sellers_path,class: "btn btn-w-m btn-primary " %>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/sellers/edit.html.erb
<%= render 'layerbegin' %>
<div class="col-lg-12">
  <div class="ibox float-e-margins">
    <div class="ibox-title">
      <h3>编辑单位</h3>
    </div>
<%= render 'form', unit: @unit %>
  </div>
</div>
<%=render 'layerend' %>

app/views/sellers/index.html.erb
<%= render 'layerbegin' %>
<div class="col-lg-12">
  <div class="ibox float-e-margins">
    <div class="ibox-title">
      <h3>商家管理</h3>
    </div>
    <div class="ibox-content">
      <table class="table table-hover table-bordered text-center">
        <thead>
        <tr>
          <th class="text-center">商家名称</th>
          <th class="text-center">商家简称</th>
          <th class="text-center">联系电话</th>
          <th class="text-center">地址</th>
          <th class="text-center">状态</th>
          <th class="text-center">操作</th>
        </tr>
        </thead>
        <tbody>
        <% @sellers.each do |seller| %>
            <tr>
              <td><%= seller.name %></td>
              <td><%= seller.shortname %></td>
              <td><%= seller.tel %></td>
              <td><%= seller.address %></td>
              <td>
                <% if seller.status == 1%>
                    启用
                <%else%>
                    停用
                <%end%>
              </td>
              <td>
                <%= link_to '查看',seller_path(seller) %>
                <%= link_to '编辑',edit_seller_path(seller) %>
                <%if session[:admin] == "admin"%>
                    <%= link_to '删除', seller, method: :delete, data: { confirm: '确认删除?' } %></td>
                <%end%>
            </tr>
        <% end %>
        </tbody>
      </table>
      <%if session[:admin] == "admin"%>
        <%= link_to "新增",new_seller_path,class: "btn btn-w-m btn-primary pull-right" %>
      <%end%>
      <br>
    </div>
  </div>
</div>
<%=render 'layerend' %>

app/views/sellers/new.html.erb
<%= render 'layerbegin' %>
<div class="col-lg-12">
  <div class="ibox float-e-margins">
    <div class="ibox-title">
      <h3>新增商家</h3>
    </div>
    <%= render 'form', seller: @seller %>
  </div>
</div>
<%=render 'layerend' %>

app/views/sellers/show.html.erb
<%= render 'layerbegin' %>
<div class="ibox-content m-b-sm border-bottom">
  <div class="p-xs">
    <div class="pull-left m-r-md">
      <img src=<%= @seller.sellerimage.url %> width="120px"  >
    </div>
    <h2><%= @seller.shortname %></h2>
    <span><%= @seller.name %></span>
  </div>
</div>

<div class="row">

  <a href=<%= seller_admins_path(@seller)%>>
    <div class="col-sm-3">
      <div class="widget style1 blue-bg">
        <div class="row">
          <div class="col-xs-4 text-center">
            <i class="fa fa-user fa-5x"></i>
          </div>
          <div class="col-xs-8 text-right">
            <span> 管理员 </span>
            <h2 class="font-bold">32</h2>
          </div>
        </div>
      </div>
    </div>
  </a>


  <a href=<%=seller_productclas_path(@seller) %> >
    <div class="col-sm-3">
      <div class="widget style1 yellow-bg">
        <div class="row">
          <div class="col-xs-4">
            <i class="fa fa-cubes fa-5x"></i>
          </div>
          <div class="col-xs-8 text-right">
            <span> 产品分类 </span>
            <h2 class="font-bold"><%=@productclacount %></h2>

          </div>
        </div>
      </div>
    </div>
  </a>

  <a href=<%= seller_products_path(@seller) + "?page=1"%> >
    <div class="col-sm-3">
      <div class="widget style1 red-bg">
        <div class="row">
          <div class="col-xs-4">
            <i class="fa fa-calendar-o fa-5x"></i>
          </div>
          <div class="col-xs-8 text-right">
            <span> 产品 </span>
            <h2 class="font-bold"><%= @seller.products.length%></h2>
          </div>
        </div>
      </div>
    </div>
  </a>

  <a href=<%= seller_buycars_path(@seller) + "?page=1"%> >
    <div class="col-sm-3">
      <div class="widget style1 red-bg">
        <div class="row">
          <div class="col-xs-4">
            <i class="fa fa-calendar-o fa-5x"></i>
          </div>
          <div class="col-xs-8 text-right">
            <span> 订单信息 </span>
            <h2 class="font-bold"><%= @seller.buycars.length%></h2>
          </div>
        </div>
      </div>
    </div>
  </a>
</div>

<div class="row">
  <a href=<%=seller_notices_path(@seller) %> >
    <div class="col-sm-3">
      <div class="widget style1 yellow-bg">
        <div class="row">
          <div class="col-xs-4">
            <i class="fa fa-cubes fa-5x"></i>
          </div>
          <div class="col-xs-8 text-right">
            <span> 通告 </span>
            <h2 class="font-bold"><%= @seller.notices.length%></h2>

          </div>
        </div>
      </div>
    </div>
  </a>
  <a href=<%=seller_weixinmenus_path(@seller) %> >
    <div class="col-sm-3">
      <div class="widget style1 yellow-bg">
        <div class="row">
          <div class="col-xs-4">
            <i class="fa fa-cubes fa-5x"></i>
          </div>
          <div class="col-xs-8 text-right">
            <span> 微信自定义菜单 </span>
            <h2 class="font-bold"><%= @seller.weixinmenus.length%></h2>
          </div>
        </div>
      </div>
    </div>
  </a>
  <a href=<%=seller_articles_path(@seller) %> >
    <div class="col-sm-3">
      <div class="widget style1 yellow-bg">
        <div class="row">
          <div class="col-xs-4">
            <i class="fa fa-cubes fa-5x"></i>
          </div>
          <div class="col-xs-8 text-right">
            <span> 文章管理 </span>
            <h2 class="font-bold"><%= @seller.articles.length%></h2>
          </div>
        </div>
      </div>
    </div>
  </a>
  <a href=<%=seller_sellermodels_path(@seller) %> >
    <div class="col-sm-3">
      <div class="widget style1 yellow-bg">
        <div class="row">
          <div class="col-xs-4">
            <i class="fa fa-cubes fa-5x"></i>
          </div>
          <div class="col-xs-8 text-right">
            <span> 微信通知管理 </span>
            <h2 class="font-bold"><%= @seller.sellermodels.length%></h2>
          </div>
        </div>
      </div>
    </div>
  </a>
</div>


<%=render 'layerend' %>