config/routes.rb
Rails.application.routes.draw do

  root :to => 'login#login'

  post "login/findlogin"
  get "login/login"
  get "login/unlogin"
  resources :systemlogs
  resources :retcauses
  resources :comments
  resources :articles
  resources :admins
  get 'logisticbuycar/update'
  get 'logisticbuycar/destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :sellers do

    resources :productclas

    resources :products

    resources :admins

    resources :sellerusers
    resources :buycars do
      #resources :logisticbuycar
      get 'logisticbuycar/index'
      get 'logisticbuycar/edit'
      get 'logisticbuycar/new'
      collection do
        get 'editstatus'
      end
      resources :retoforders do
        member do
          get 'setretok'
          get 'setretno'
          get 'setlogisticok'
        end
      end
      member do
        post 'setsellererr'
      end
    end
    resources :notices
    resources :weixinmenus
    resources :articles do
      resources :comments do
        member do
          get  'publecomm'
          get  'publedel'
        end
      end
    end
    resources :sellermodels do
      resources :modelconts
    end
  end

  resources :logistics
  resources :logisticorders
  resources :stables

  resources :recepitaddres

  resources :orders
  resources :userpwds
  resources :users

  resources :notices

  resources :weixinmenus do
    collection do
      get 'saveweixin'
      get 'saveid'
      get 'delid'
      get 'loading'
    end
  end

  resources :apis do
    collection do
      get 'getreceoitdefault'
      get 'getseller'
      get 'getproductlist'
      get 'getproductcontent'
      get 'getproname'
      get 'getrecepit'
      get 'getbuycarfrom'
      get 'getbuycarlist'
      get 'getreceoitadd'
      get 'getrecepitone'
      get 'getreceoitedit'
      get 'getreceoitdel'
      get 'getreceoitdefa'
      get 'getnotice'
      post 'weixingetpost'
      get 'weixingetpost'
      get 'getweixinimg'
      get 'getwxopenid'
      get 'getbuycaradd'
      get 'setreceive'
      get 'getbuycarplay'
      get 'getbuycarconfirm'
      get 'getuserupname'
      get 'setuserupname'
      get 'getthreename'
      get 'getsenondname'
      get 'getreferralname'
      get 'getwxpublicqrcode'
      get 'getwxpubliopenid'
      get 'getsellerqrcode'
      get 'getuserpswds'
      get 'setuserpswds'
      get 'getak'
      get 'getwxgetrich'
      get 'getarticles'
      get 'getarticleopenid'
      get 'getarticlecontent'
      get 'setcomment'
      get 'getsystemlog'
      get 'getbuycaraftersales'
      get 'setafterone'
      get 'getlogistics'
      get 'getafterlogistics'
      get 'setlogistics'
      get 'getretcauses'
      get 'getwxposanopenid'
      get 'getbuycardel'
      post 'prepaytrue'
      get 'getbuycartruemoney'
    end
  end

  resources :weixinlogs

end

app/models/sellermodel.rb
class Sellermodel < ApplicationRecord
  belongs_to :seller
  has_many :modelconts ,dependent: :destroy
end

app/controllers/sellermodels_controller.rb
class SellermodelsController < ApplicationController
  before_action :authenticate_role
  before_action :set_seller, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  before_action :set_sellermodel, only: [:show, :edit, :update, :destroy]

  def index
    @sellermodels = @seller.sellermodels
    @wxjson = getwxmodel(@seller.id)
    zt = 0
    model = Array.new
    @sellermodels.each do |sm|
      zt = 0
      @wxjson.each do |wx|
        if sm.modeid ==  wx['template_id']
          zt = 1
          model.push(wx)
          sm.wxtype = 0
        end
      end
      if zt == 0
        #sm.destroy
        sm.wxtype = 1
      end
      sm.save
    end
    zt = Array.new
    @wxjson.each do |wx|
      zt.push(wx)
    end
    zt = zt - model
    if zt.length
      zt.each do |newmod|
        mod = @seller.sellermodels.new
        mod.modeid = newmod['template_id']
        mod.stype = 0
        mod.save
        str = newmod['content']
        str = str.split("\n")
        str.each do |con|
          if con != ''
            sta = con.index('{{') + 2
            ennum = con.index('.') - 1
            con = con[sta..ennum]
            modelcont = Modelcont.new
            modelcont.sellermodel_id = mod.id
            modelcont.wxname = con
            modelcont.stype = 0
            modelcont.save
          end
        end
      end
    end
    @sellermodels = @seller.sellermodels
    #modelout(1,2,'o5E2BwRcsWxBvS-vrrbd76blwjGE',2)
  end

  def edit
    @stable = Stable.all
    @wxjson = getwxmodel(@seller.id)
  end

  def new
    @stable = Stable.all
    @sellermodel = @seller.sellermodels.new
    @wxjson = getwxmodel(@seller.id)
  end

  def create
    @sellermodel = Stable.new(sellermodel_params)
    respond_to do |format|
      if @stable.save
        format.html { redirect_to seller_sellermodels_url, notice: 'Retoforder was successfully created.' }
        format.json { render seller_sellermodels_url, status: :created, location: @sellermodel }
      else
        format.html { render :new }
        format.json { render json: @sellermodel.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @sellermodel.update(sellermodel_params)
        modelcon = modelconts_params
        modelcon.each do |mod|
          con = Modelcont.find(mod)
          con.tbname = modelcon[mod]['tbname']
          con.content = modelcon[mod]['content']
          con.stype = modelcon[mod]['stype']
          con.save
        end
        format.html { redirect_to seller_sellermodels_url, notice: 'Retoforder was successfully updated.' }
        format.json { render seller_sellermodels_url, status: :ok, location: @sellermodel }
      else
        format.html { render :edit }
        format.json { render json: @sellermodel.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    delwxmodel(@seller.id,@sellermodel.modeid)
    @sellermodel.destroy
    respond_to do |format|
      format.html { redirect_to seller_sellermodels_url, notice: '删除成功' }
      format.json { head :no_content }
    end
  end

  private

  def getwxmodel(sellerid)
    token = getaccesstoken(sellerid)
    wxjson = gethtml('https://api.weixin.qq.com/cgi-bin/template/get_all_private_template?access_token=' + token)
    wxjson = JSON.parse(wxjson)
    if wxjson['template_list']
      wxjson = wxjson['template_list']
      wxjson = wxjson.to_a
      wxjson.delete_at(0)
      wxjson = JSON.parse(wxjson.to_json)
    else
      wxjson = Array.new
    end
    return wxjson
  end

  def delwxmodel(sellerid,modelid)
    token = getaccesstoken(sellerid)
    ret = posthtml('https://api.weixin.qq.com/cgi-bin/template/del_private_template?access_token=' + token,'{"template_id":"' + modelid + '"}')
    return ret
  end

  def set_seller
    @seller = Seller.find(params[:seller_id])
  end

  def set_sellermodel
    @sellermodel = Sellermodel.find(params[:id])
  end
  def modelconts_params
    params[:sellermodel][:modelcont]
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def sellermodel_params
    params.require(:sellermodel).permit(:tablename, :stype, :seller_id, :modeid)
  end
end

app/helpers/sellermodels_helper.rb
module SellermodelsHelper
end

app/views/sellermodels/_form.html.erb
<script>
    $(document).ready(function(){
        $("#claselect").val($("#clainput").val());
        $("#claselect").change(function(){
            $("#clainput").val($("#claselect").val());
        });
        $('#smt').click(function(){
            if($('#clainput').val()==''){
                toastr.error('请选择表名');
                return false;
            }
        });
    });
</script>
<div class="ibox-content form-horizontal m-t">
  <div class="form-group">
    <%= form_for([@seller,@sellermodel],:html => {:class=>'form-horizontal m-t',:multipart => true}) do |f| %>
        <% if @sellermodel.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@sellermodel.errors.count, "error") %> prohibited this retoforder from being saved:</h2>

              <ul>
                <% @sellermodel.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
              </ul>
            </div>
        <% end %>
        <%= f.hidden_field :seller_id %>
        <div class="form-group">
          <label class="col-sm-3 control-label">表名：</label>
          <div class="col-sm-5">
            <%= f.hidden_field :tablename,class:"form-control",id:'clainput' %>
            <select class="form-control m-b" name="account" id="claselect">
              <%= @stable.each do |sta|%>
                  <option value=<%=sta.name%>><%= sta.lable %></option>
              <% end %>
            </select>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label">状态：</label>
          <div class="col-sm-5">
            <%= f.number_field :stype,class:"form-control" %>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label">模板ID：</label>
          <div class="col-sm-5">
            <%= f.text_field :modeid,class:"form-control" %>
          </div>
        </div>
        <div class="ibox-content">
          <table class="table table-hover table-bordered text-center">
            <thead>
            <tr>
              <th class="text-center">字段名</th>
              <th class="text-center">微信字段</th>
              <th class="text-center">内容</th>
              <th class="text-center">状态</th>
            </tr>
            </thead>
            <tbody>
            <% @sellermodel.modelconts.each do |cont| %>
                <%= f.fields_for cont, index: cont.id do |cont_form|%>
                    <tr>
                      <td><%= cont_form.text_field :tbname , style:'width: 100%;'%></td>
                      <td><%= cont_form.text_field :wxname , style:'width: 100%;' , readonly:'true'%></td>
                      <td><%= cont_form.text_field :content , style:'width: 100%;'%></td>
                      <td><%= cont_form.number_field :stype , style:'width: 100%;'%></td>
                    </tr>
                <% end %>
            <% end %>
            </tbody>
          </table>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label"></label>
          <div class="col-sm-5 text-right">
            <%= f.submit '确定',class: "btn btn-w-m btn-primary",id:'smt'%>&nbsp;<%= link_to "返回",seller_sellermodels_path(@seller),class: "btn btn-w-m btn-primary " %>
          </div>
        </div>
    <% end %>
    <div class="ibox-content">
      <table class="table table-hover table-bordered text-center">
        <thead>
        <tr>
          <th class="text-center">模版ID</th>
          <th class="text-center">标题</th>
          <th class="text-center">模板内容</th>
          <th class="text-center">模板实例</th>
        </tr>
        </thead>
        <tbody>
        <% @wxjson.each do |wxj| %>
            <tr>
              <td><%= wxj['template_id'] %></td>
              <td><%= wxj['title'] %></td>
              <td><%= wxj['content'] %></td>
              <td><%= wxj['example'] %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/sellermodels/edit.html.erb
<%= render 'layerbegin' %>
<div class="col-lg-12">
  <div class="ibox float-e-margins">
    <div class="ibox-title">
      <h3>编辑对应关系</h3>
    </div>
    <%= render 'form', sellermodel: @sellermodel %>
  </div>
</div>
<%=render 'layerend' %>

app/views/sellermodels/index.html.erb
<%= render 'layerbegin' %>
<div class="col-lg-12">
  <div class="ibox float-e-margins">
    <div class="ibox-title">
      <h3>微信通知管理</h3>
    </div>
    <div class="ibox-content">
      <table class="table table-hover table-bordered text-center">
        <thead>
        <tr>
          <th class="text-center">表名</th>
          <th class="text-center">模板ID</th>
          <th class="text-center">状态</th>
          <th class="text-center">使用状态</th>
          <th class="text-center">操作</th>
        </tr>
        </thead>
        <tbody>
        <% @sellermodels.each do |ret| %>
            <tr>
              <td><%= ret.tablename %></td>
              <td><%= ret.modeid %></td>
              <td><%= ret.stype %></td>
              <td>
                <%if ret.wxtype == 1%>
                    已在微信中删除该模板删除
                <%else%>
                    正常
                <%end%>
              </td>
              <td>
                <%if ret.wxtype != 1%>
                    <%= link_to '编辑',edit_seller_sellermodel_path(@seller,ret) %>
                <%end%>
                <%= link_to '删除', [@seller,ret], method: :delete, data: { confirm: '确认删除?' } %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
      <%= link_to "返回",seller_path(@seller),class: "btn btn-w-m btn-info " %>
      <div class="btn-group  btn-w-m pull-right" role="group">
        <%= link_to "新增",new_seller_sellermodel_path,class: "btn btn-w-m btn-primary pull-right" %>

      </div>
      <br>
    </div>
  </div>
</div>
<%=render 'layerend' %>

app/views/sellermodels/new.html.erb
<%= render 'layerbegin' %>
<div class="col-lg-12">
  <div class="ibox float-e-margins">
    <div class="ibox-title">
      <h3>新增对应关系</h3>
    </div>
    <%= render 'form', sellermodel: @sellermodel %>
  </div>
</div>
<%=render 'layerend' %>